apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../apps/pixelcore-api

namespace: pixelcore

commonLabels:
  environment: production

replicas:
- name: api
  count: 5

images:
- name: pixelcore/api
  newTag: v1.0.0
