apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pixelcore-dev

namePrefix: dev-

commonLabels:
  environment: development

bases:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yaml
  - resource-patch.yaml

configMapGenerator:
  - name: pixelcore-config
    behavior: merge
    literals:
      - APP_ENV=development
      - RUST_LOG=debug

images:
  - name: ghcr.io/your-org/pixelcore/backend
    newTag: develop
  - name: ghcr.io/your-org/pixelcore/frontend
    newTag: develop
